config/routes.rb
Rails.application.routes.draw do
  resources :bugs
  root to: 'pages#home'
  devise_for :users, controllers: # becuase we have customized them
    {
      :sessions => "users/sessions" , 
      :registrations => "users/registrations"
    }
  post 'bugs/editstatus' => 'bugs#editstatus', :as => :editstatus_bugs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bug.rb
class Bug < ApplicationRecord
  belongs_to :user
  has_attached_file :image , styles: {large: "600x600>" , medium: "300x300>" , small: "200x200>"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/ 
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_bug, only: [:show, :edit, :update, :destroy, :editstatus]
  #This line is causing error 
  #before_filter :authenticate_user!

  #after_action :verify_authorized, except: :index
  #after_action :verify_authorized, except:  [:index ,:new], unless: :devise_controller?
  #after_action :verify_authorized, except:  [:index], unless: :devise_controller?
  #You have to call authorization on all methods excpt these ^^^
  #after_action :verify_authorized, except:  , unless: :devise_controller?
  #if there is no edit then we have Skip_pundit_error  vvvvv
  after_action :verify_policy_scoped, except: [:index,:show, :new, :create ,:edit ,:destroy ,:update ,:editstatus], unless: :skip_pundit?
  #after_action :verify_policy_scoped, only: :index

  # GET /bugs
  # GET /bugs.json

  def editstatus
    #@bug = Bug.where(id: params[:id], user_id: params[:user_id])
    if params[:change_status] == "Resolved"
      @bug.update(status: "Resolved")
    #else
    elsif params[:change_status] == "Done"
      @bug.update(status: "Done")
    else 
      @bug.update(status: "Active")
    #  @groupUser.update(membership: "denied")
    end
    #redirect_to groupshow_path(:id => params[:id])
    redirect_to bugs_path(@bug)
  end


  def index
    @bugs = Bug.all
    #@bug = Bug.find(params[:id])
    authorize @bugs
    #here we will render different views with respect to users
  end

  # GET /bugs/1
  # GET /bugs/1.json
  def show
    #authorize @bug
  end

  # GET /bugs/new
  def new
    @bug = Bug.new
    #if authorized not called here , it will give an error
    #if it runs and return false , only then it will be able to give the error message i.e application-con
    authorize @bug
  end

  # GET /bugs/1/edit
  def edit
    #authorize @bug
  end

  # POST /bugs
  # POST /bugs.json
  def create
    
    @bug = Bug.new(bug_params)
    authorize @bug
    respond_to do |format|
      if @bug.save
        format.html { redirect_to @bug, notice: 'Bug was successfully created.' }
        format.json { render :show, status: :created, location: @bug }
      else
        format.html { render :new }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
    
    
  end

  # PATCH/PUT /bugs/1
  # PATCH/PUT /bugs/1.json
  def update
    respond_to do |format|
      if @bug.update(bug_params)
        format.html { redirect_to @bug, notice: 'Bug was successfully updated.' }
        format.json { render :show, status: :ok, location: @bug }
      else
        format.html { render :edit }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
    #authorize @bug
  end

  # DELETE /bugs/1
  # DELETE /bugs/1.json
  def destroy
    authorize @bug
    #why the bug is being destroyed even after authorize @bug
    @bug.destroy
    respond_to do |format|
      format.html { redirect_to bugs_url, notice: 'Bug was successfully destroyed.' }
      format.json { head :no_content }
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bug
      @bug = Bug.find(params[:id])
      authorize @bug
    end

    # Only allow a list of trusted parameters through.
    def bug_params
      params.require(:bug).permit(:title, :description, :status, :user_id , :image)
    end

    
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/views/bugs/_form.html.erb
<%= form_with(model: bug, local: true , html: {multipart: true }) do |form| %>
  <% if bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

      <ul>
        <% bug.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bugs/edit.html.erb
<div class = 'col-sm-offset-5'>
    <h1>Editing Bug</h1>

    <%= render 'form', bug: @bug %>

    <%= link_to 'Show', @bug %> |
    <%= link_to 'Back', bugs_path %>
</div>

app/views/bugs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bugs</h1>

<table cellspacing="10">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bugs.each do |bug| %>
      <% if ((bug.status == "Active") && (policy(bug).Developer_bug_view?) && (bug.user_id == current_user.id)) %>
        <tr>
          <td><%= bug.title %></td>
          <td><%= bug.description %></td>
          <td><%= bug.status %></td>
          <td><%= bug.user_id %></td>
          <td><%= image_tag bug.image.url(:small) %></td>
          <% if policy(bug).is_Admin_or_QA? %>
            <td><%= link_to 'Show', bug %></td>
            <td><%= link_to 'Edit', edit_bug_path(bug) %></td>
            <td><%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
          <% if policy(bug).Developer_bug_view? %>
            <td><%= link_to 'Mark Resolved', {:controller => "bugs",
                                   :action => "editstatus",
                                   :id => bug.id,
                                   :change_status => "Resolved"}, method: 'post', class: "btn btn-sm btn-success" %>
          <% end %>
        </tr>
      <% end %>  
      <% if (((bug.status == "Active") ||(bug.status == "Resolved") ) && (policy(bug).QA_bug_view?)) %>
        <tr>
          <td><%= bug.title %></td>
          <td><%= bug.description %></td>
          <td><%= bug.status %></td>
          <td><%= bug.user_id %></td>
          <td><%= image_tag bug.image.url(:small) %></td>
          <% if policy(bug).is_Admin_or_QA? %>
            <td><%= link_to 'Show', bug %></td>
            <td><%= link_to 'Edit', edit_bug_path(bug) %></td>
            <td><%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
          <% if ((policy(bug).QA_bug_view?) && (bug.status == "Resolved"))%>
            <td><%= link_to 'Mark Done', {:controller => "bugs",
                                   :action => "editstatus",
                                   :id => bug.id,
                                   :change_status => "Done"}, method: 'post', class: "btn btn-sm btn-success" %>
            <% if (bug.status != "Active") %>
              <td><%= link_to 'Active Again', {:controller => "bugs",
                                     :action => "editstatus",
                                     :id => bug.id,
                                     :change_status => "Active"}, method: 'post', class: "btn btn-sm btn-success" %>
            <% end %>
          <% end %>
        </tr>
      <% end %> 
      <% if (policy(bug).Admin_bug_view?) %>
        <tr>
          <td><%= bug.title %></td>
          <td><%= bug.description %></td>
          <td><%= bug.status %></td>
          <td><%= bug.user_id %></td>
          <td><%= image_tag bug.image.url(:small) %></td>
          <% if policy(bug).is_Admin_or_QA? %>
            <td><%= link_to 'Show', bug %></td>
            <td><%= link_to 'Edit', edit_bug_path(bug) %></td>
            <td><%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
          <% if policy(bug).Developer_bug_view? %>
            <td><%= link_to 'Mark Resolved', policy(bug).change_to_resolve %></td>
          <% end %>
        </tr>
      <% end %> 
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bug', new_bug_path %>

app/views/bugs/new.html.erb
<h1>New Bug</h1>

<%= render 'form', bug: @bug %>

<%= link_to 'Back', bugs_path %>

app/views/bugs/show.html.erb
<h1>Here is the Bug that you want to see</h1>
</li>
</li>
<p id="notice"><%= notice %></p>
<%= image_tag @bug.image.url(:medium)%>
<p>
  <strong>Title:</strong>
  <%= @bug.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bug.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @bug.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @bug.user_id %>
</p>

<%= link_to 'Edit', edit_bug_path(@bug) %> |
<%= link_to 'Back', bugs_path %>